### ISSUE TITLE
AddressNotFoundException error

### ISSUE THREAD

**Issue by westor7** [maxmind/GeoIP2-dotnet#113]
Hello,

I am trying to that code https://pastebin.com/pa8LWXsA but when the IP is 103.8.195.34 i am getting an error.

Error Message: 

```
Plugin MaxMind.GeoIP2.dll caused an error
 
 MaxMind.GeoIP2.Exceptions.AddressNotFoundException: The address 103.8.195.34 is not in the database.
   at MaxMind.GeoIP2.DatabaseReader.Execute[T](String ipStr, IPAddress ipAddress, String type, Boolean throwOnNullResponse)
   at MaxMind.GeoIP2.DatabaseReader.Execute[T](String ipStr, String type, Boolean throwOnNullResponse)
   at MaxMind.GeoIP2.DatabaseReader.Country(String ipAddress)
   at GeoIP2CountryPlugin.GeoIP2CountryPlugin.GeoIPIdentifier(RegisteredIdentifierArgs argument)
```

Any idea how to fix this error in the above code? 

- Thanks!

**Comment by oschwald** [comment]
Please [see the documentation](https://github.com/maxmind/GeoIP2-dotnet#database). That exception is thrown if the IP is not in the database. You can either catch the exception or switch to [TryCountry](http://maxmind.github.io/GeoIP2-dotnet/doc/v3.1.0/html/M_MaxMind_GeoIP2_DatabaseReader_TryCountry.htm).
